# Generated by Django 4.2.15 on 2025-06-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Группы',
                'verbose_name_plural': 'Группа',
                'db_table': 'group',
            },
        ),
    ]
