version: '3.8'

services:
  # Сервис базы данных PostgreSQL
  db:
    image: postgres:15
    container_name: zabgu-db
    restart: always
    environment:
      - POSTGRES_USER=zabgu_user
      - POSTGRES_PASSWORD=strong_password
      - POSTGRES_DB=zabgu_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Пробрасываем порт для удобства отладки

  # Сервис нашего Spring-приложения
  app:
    build: . # Собирать образ из Dockerfile в текущей директории
    container_name: zabgu-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db # Запускать только после того, как запустится сервис 'db'
    environment:
      # --- Настройки для подключения к БД ---
      # 'db' - это имя сервиса PostgreSQL, Docker Compose автоматически сделает его доступным по этому хосту
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/zabgu_db
      - SPRING_DATASOURCE_USERNAME=zabgu_user
      - SPRING_DATASOURCE_PASSWORD=strong_password
      # --- Настройка для сохранения картинок ---
      # Указываем путь ВНУТРИ контейнера, куда будут сохраняться файлы
      - FILE_UPLOAD_DIR=/app/uploads
    volumes:
      # Связываем папку /app/uploads внутри контейнера с томом 'uploads_data'
      - uploads_data:/app/uploads

# Определяем "именованные тома" (volumes) для постоянного хранения данных
volumes:
  postgres_data: # Данные для PostgreSQL
  uploads_data:  # Загруженные картинки