# Generated by Django 5.0.14 on 2026-06-06 09:10

import booking.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True, verbose_name='Номер домика')),
                ('capacity', models.PositiveSmallIntegerField(default=4, verbose_name='Вместимость (койко-мест)')),
                ('price_staff_full_cabin', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за домик сутки (Сотрудник)')),
                ('price_student_bed', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за койко-место/сутки (Студент)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание домика')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступен для бронирования')),
            ],
            options={
                'verbose_name': 'Домик',
                'verbose_name_plural': 'Домики',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_number', models.CharField(db_index=True, max_length=12, unique=True, verbose_name='Номер бронирования')),
                ('user_role', models.CharField(choices=[('STAFF', 'Сотрудник'), ('STUDENT', 'Студент')], max_length=10, verbose_name='Роль пользователя')),
                ('num_beds_booked', models.PositiveSmallIntegerField(verbose_name='Забронировано мест')),
                ('start_date', models.DateField(verbose_name='Дата заезда')),
                ('end_date', models.DateField(verbose_name='Дата выезда')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итоговая стоимость')),
                ('contact_name', models.CharField(max_length=255, verbose_name='ФИО контактного лица')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('department', models.CharField(blank=True, max_length=255, null=True, verbose_name='Структурное подразделение')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность')),
                ('faculty', models.CharField(blank=True, max_length=255, null=True, verbose_name='Факультет')),
                ('academic_group', models.CharField(blank=True, max_length=50, null=True, verbose_name='Академическая группа')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает оплаты'), ('RECEIPT_UPLOADED', 'Чек загружен'), ('PAYMENT_CONFIRMED', 'Оплата подтверждена'), ('CONFIRMED', 'Бронирование подтверждено'), ('CANCELLED', 'Бронирование отменено'), ('REJECTED', 'Оплата отклонена')], default='PENDING', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('expires_at', models.DateTimeField(verbose_name='Время истечения брони')),
                ('cabin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='booking.cabin', verbose_name='Домик')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО гостя')),
                ('category', models.CharField(choices=[('ADULT', 'Взрослый'), ('CHILD_15', 'Ребенок до 15 лет'), ('CHILD_3', 'Ребенок до 3 лет')], default='ADULT', max_length=10, verbose_name='Категория')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='booking.booking', verbose_name='Бронирование')),
            ],
            options={
                'verbose_name': 'Отдыхающий',
                'verbose_name_plural': 'Отдыхающие',
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=booking.models.secure_receipt_upload_path, verbose_name='Файл чека')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('user_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий пользователя')),
                ('admin_comment', models.TextField(blank=True, null=True, verbose_name='Причина отклонения (для админа)')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='booking.booking', verbose_name='Бронирование')),
            ],
            options={
                'verbose_name': 'Чек об оплате',
                'verbose_name_plural': 'Чеки об оплате',
            },
        ),
    ]
