version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: task_manager_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: task_manager_db
    ports:
      # Внешний порт 5433 (на вашем ПК) пробрасывается на стандартный внутренний порт 5432 PostgreSQL
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: