# Generated by Django 4.2.15 on 2025-06-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Пара')),
                ('time_start', models.TimeField(verbose_name='Время начала пары')),
                ('time_end', models.TimeField(verbose_name='Время окончания пары')),
            ],
            options={
                'verbose_name': 'Расписание звонков',
                'verbose_name_plural': 'Расписание звонков',
                'db_table': 'time',
            },
        ),
    ]
