# Generated by Django 5.0.14 on 2026-06-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='category',
            field=models.CharField(choices=[('ADULT', 'Взрослый'), ('CHILD_10', 'Ребенок до 10 лет'), ('CHILD_3', 'Ребенок до 3 лет')], default='ADULT', max_length=10, verbose_name='Категория'),
        ),
    ]
