# Generated by Django 5.0.14 on 2026-06-16 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_guest_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='second_cabin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='second_bookings', to='booking.cabin', verbose_name='Второй домик'),
        ),
    ]
