
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankcorp_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update # Автоматическое создание таблиц
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080